audit_header: false
title: Yuma Real Estate Video Blog with Quincy Smith
description: Our mission at ERA Matt Fischer Realtor is to be your best resource for Yuma real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The ERA Matt Fischer Realtor, your professional Yuma Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Quincy Smith
  title:
  license_number:
  about_markdown: |
    As a non-native resident to Yuma, AZ, Quincy knew the unique charm and home town feel of our amazing community were right for him to call it home. With more than 15 years of experience with our local real estate market, Quincy brings a breadth of expertise to the team.

    Quincy knows first-hand how challenging residential resales can be, and that’s why his experience is so valuable. Since joining the ERA team, he quickly became one our most trusted and top-producing real estate agents in our local market. Quincy attributes this success to passion for people — not pitches and sales techniques. Through his people-first approach, Quincy stepped in as ERA’s coach and trainer in 2016. Now, as the company broker, he works tirelessly on the commitment that led him into the real estate business — helping people succeed.

    Quincy believes that a broker should not compete against their agents but should work full time to support and foster their growth. Quincy has turned his attention to creating an ideal environment for committed agents to create amazing careers that fully support their lives and aspirations.
  brand: ERA Matt Fischer Realtor
  brokerage:
  market: Yuma
  address: '2755 S 4th Ave, #100 Yuma, AZ 85364'
  phone: 928-919-2599
  phone_type:
  phone2:
  phone2_type:
  email: quincy@erayuma.com
  url: http://www.AtHomeInYuma.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://www.athomeinyuma.com/what-is-my-home-worth
  second_CTA_text: Home Search
  second_CTA_URL: http://www.athomeinyuma.com/search/advanced_search/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your Yuma Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: https://www.athomeinyuma.com/what-is-my-home-worth

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a Yuma Home?"
    CTA_text2: "Search the entire MLS for your Yuma home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: http://www.athomeinyuma.com/search/advanced_search/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://business.facebook.com/MattFischerRealtorGroup/?business_id=10153283000255325
  linkedin_url:
  youtube_url: https://www.youtube.com/channel/UCejw4LWA29P5AVr_RfEKY0g
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Yuma Real Estate Podcast with Quincy Smith'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Yuma Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from ERA Matt Fischer Realtor - your professional Yuma Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Yuma, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Quincy Smith'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Yuma Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#920237'
  theme_color: '#0B3278'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#920237'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
